spring:
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
   datasource:
     url: jdbc:mysql://127.0.0.1:3306/demo?useSSL=false&serverTimezone=GMT%2B8
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
server:
   port: 8011

logging:
   level:
     org.springframework.data: DEBUG